name: Run IRCC Draw Scraper

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Download Chrome for Testing and ChromeDriver
      run: |
        mkdir -p /opt/chrome
        wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64/* /opt/chrome/
        sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome

        wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.111/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py

    - name: Commit updated CSV
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add data/ircc_draw_history.csv
        git commit -m "🤖 Auto-update IRCC draws"
        git push
      continue-on-error: true
