name: Scrape IRCC Draw Data

on:
  schedule:
    - cron: '0 0 */2 * *'  # Every 2 days at 00:00 UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas beautifulsoup4

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push CSV if changed
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ircc_draw_history.csv

        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "🔄 Auto-update IRCC draw data"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
        fi
